### ISSUE TITLE
👋 Hi! I build a CryptoBox use waills

### ISSUE THREAD

**Issue by istommao** [wailsapp/awesome-wails#15]
Hi! I build a CryptoBox use waills
Can i add it to Open Source Apps List

Github: https://github.com/istommao/CryptoBox

![image](https://user-images.githubusercontent.com/5070879/216220999-08f56697-ce5b-4622-ac8e-d5505ea5d69a.png)

**Comment by leaanthony** [comment]
Feel free to open a PR 👍

**Comment by istommao** [comment]
@leaanthony 👌OK 😄
