### ISSUE TITLE
Work display

### ISSUE THREAD

**Issue by yhy0** [wailsapp/awesome-wails#22]
I am writing to request the opportunity to showcase my application developed using Wails on your official platform. I have created a project called "ChYing," and its source code can be found at the following GitHub repository: https://github.com/yhy0/ChYing.
Project introduction：https://github.com/yhy0/ChYing/blob/main/README-en.md

**Comment by misitebao** [comment]
First of all thanks for using Wails, you just need to submit a PR.

**Comment by yhy0** [comment]
Thank you very much for wails.
